### ISSUE TITLE
NS symlink

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.Layer2#24]
Not sure if the ns symlink under the zenpack directory is intentional or not?  When installed the egg i had a link or a duplicate zenpack directory tree (forget which) i can see the latest commit shows that directory updated..im assuming its some kind of dev environment relic?

https://github.com/zenoss/ZenPacks.zenoss.Layer2/blob/develop/ns

**Comment by ssbunyk** [comment]
Yes, it's mine. It helps to open files with code faster. Sometimes I forget, and add it to commit. But now I'm added global excludesfile option for git and will remove it from develop branch.

Sorry that I'm answering this so late, I just missed notification about this issues somehow.
