### ISSUE TITLE
event keys/classes event handling.

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.Layer2#71]
Is it possible to add event keys/event class keys rather than hard coding event classes for the events generated by this zenpack.

**Comment by ssbunyk** [comment]
I believe this should be possible. Created a Jira for that and will do in a week or two.

**Comment by dougsyer** [comment]
thanks!   that helps alot.

**Comment by ssbunyk** [comment]
Here is a pull-request with fixes: https://github.com/zenoss/ZenPacks.zenoss.Layer2/pull/74
